### ISSUE TITLE
File path incorrect

### ISSUE THREAD

**Issue by swilson-pro** [learn-co-curriculum/phase-4-rails-route-params-readme#3]
### Canvas Link

https://learning.flatironschool.com/courses/5209/assignments/205114?module_item_id=470110

### Concern

Hi Team, 
The file path that reads # app/controllers/posts_controller.rb should instead read # app/controllers/cheeses_controller.rb

### Suggested Changes

change the file path

**Comment by jlboba** [comment]
Hello, and thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved.
Note, however, that if you are working in Canvas the changes may not show up
there, but they will for future students. We appreciate your support! 💙
